name: Build and Manage .NET Projects

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout dotnetProject1
    - name: Checkout dotnetProject1
      uses: actions/checkout@v2
      with:
        repository: 'PankajShendeGit/dotnetProject1'
        path: 'dotnetProject1'
    
    # Build dotnetProject1
    - name: Build dotnetProject1
      run: |
        cd dotnetProject1\dotnetproject1
        dotnet build --configuration Release
    
    # Optionally, copy the DLLs to a specific folder. Adjust the source and destination paths as needed.
    - name: Copy DLLs to a folder
      run: |
        New-Item -ItemType Directory -Force -Path ${{ github.workspace }}\dlls
        Copy-Item dotnetProject1\dotnetproject1\bin\Release\net6.0\*.dll ${{ github.workspace }}\dlls\
    
    # Checkout dotnetProject2
    - name: Checkout dotnetProject2
      uses: actions/checkout@v2
      with:
        repository: 'PankajShendeGit/dotnetProject2'
        path: 'dotnetProject2'
    
    # Build dotnetProject2, assuming it needs the DLLs from dotnetProject1
    - name: Build dotnetProject2
      run: |
        cd dotnetProject2\dotnetProject2
        # If specific DLLs from dotnetProject1 are needed, ensure they're correctly referenced or copied to expected locations
        dotnet restore
        dotnet build --configuration Release
